### ISSUE TITLE
Failed to Init Application Error Message

### ISSUE THREAD

**Issue by fdfcadmin** [pgptool/pgptool#101]
I recently switch to another company and my pgptool is pointing to a directory that I no longer have access to. How can I change it? I uninstalled the program and re-installed but I keep getting the same error message. Once I click ok nothing happens... This is a great tool that I would like to continue to use.
![pgp error](https://user-images.githubusercontent.com/35743846/35298517-6dbb70cc-0050-11e8-8bbd-315c33ecdb5b.JPG)

**Comment by skarpushin** [comment]
@fdfcadmin , I'm sorry to hear you faced this error. Error message is a little bit incomplete thus it's hard to say what exactly went wrong and how to fix it. 

Can I ask you to send me (sergey.v.karpushin@gmail.com) the log file `pgptool-gui.log` which could be found in the user home folder)? Before sending please review it to make sure there is no sensitive information included. 

It appears that at some point you've changed the location of temporary folder (see screen shot below). Is that right?
![pgptool_change temp folder](https://user-images.githubusercontent.com/4069181/35365408-70ecc41a-0142-11e8-88d2-0ff4ab573053.png)

**Comment by skarpushin** [comment]
@fdfcadmin , I've created new version 0.4.3.0 which might address your case (I don't know for sure unless I see log file). Please install it and let me know if it helps: https://github.com/pgptool/pgptool/releases/tag/v0.4.3.0
If it helps I don't really need to see the log file.

**Comment by skarpushin** [comment]
Ok, it appears new version solved the problem (per feedback I received on my personal email)
