### ISSUE TITLE
Feature: When key file contains both private and public keys -- import both of them

### ISSUE THREAD

**Issue by user9209** [pgptool/pgptool#156]
PGP Tool 0.5.1.0 (Win 8.1)

If the file containing

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

...
-----END PGP PUBLIC KEY BLOCK-----
-----BEGIN PGP PRIVATE KEY BLOCK-----
Version: GnuPG v2

...
-----END PGP PRIVATE KEY BLOCK-----
```
it only imports the public key, the secret key is ignored.
Such file is generated by the enigmail plugin 2.0.4 at exporting the secret key.

One workaround is to remove the 
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

...
-----END PGP PUBLIC KEY BLOCK-----
```
block so the secret block is imported.

**Comment by skarpushin** [comment]
@user9209 thank you for your feedback, I'll see whats happening there in the next couple weeks.

**Comment by skarpushin** [comment]
OpenPGP RFC doesn't seem to indicate that multiple armored headers are allowed in one file. 
https://tools.ietf.org/html/rfc4880
Therefore I'm changing the status of this issue from Fix to Improvement.

**Comment by user9209** [comment]
@skarpushin Thank you for your commitment and fast answer.

**Comment by skarpushin** [comment]
Design:
* Need to impl iterable stream which can divide source input stream separated by blocks headers/footers
* Will need to impl something in a ballpark of: https://github.com/Azure/azure-storage-java/blob/master/microsoft-azure-storage/src/com/microsoft/azure/storage/blob/SubStream.java

**Comment by user9209** [comment]
@skarpushin Thank you very much. It works well for many keys.

Only one key does not work, I do not know why. Is not related to key size or key info.
Maybe this key is not valid. Error message was:

> 0 key(s) read successfully, 1 key(s) read error
> 
> xxxxxx.asc
Unexpected exception: Can't read key file -> Unexpected exception: Error happened while parsing key -> Iterator failed to get next object: unknown object in stream: 7 -> Input/Output error unknown object in stream: 7

You code may be ok, maybe it is only the key.

**Comment by skarpushin** [comment]
@user9209, thanks for the response. I have couple troubleshooting questions:

- if it is a public key, can you email it to me (sergey.v.karpushin@gmail.com)? I'll try to see what's wrong with it. 
- Were you able to import it to PGP tool before? 
- Were you able to import it to other PGP applications?

**Comment by user9209** [comment]
@skarpushin It's a private key.

- 8192 bit key size
- RSA
- Password protected


Key is not shown even it ends as .asc.

![image](https://user-images.githubusercontent.com/9293951/51721591-ca99e080-2052-11e9-9a86-4d5239306564.png)


It seems to be an error resulting the export of enigmail.
I exported the same key with gpg and enigmail again but it does work without problems.

gpg can import only the public key of the not working private key.
So your tool works well, my key file seems to be damaged (size correct but maybe encryption demaged).

**Comment by skarpushin** [comment]
@user9209 I see. Maybe you can create new/dummy private key with same properties and send it to me? Otherwise I don't know how else I can get to bottom of this. 

Btw, I'm not an expert in this, so I'm going to tell you more than I know =)
There are certain key size limitations in Java due to (believe it or not) laws in different countries. Maybe 8k key just exceeds restricted key size. Or maybe it's Bouncycastle limitation. Bouncycastle  - is the PGP implementation I use. 

p.s. when designing UX (user experience) of this application I tried to follow "trimmed" approach. If operation is not possible or would lead to errors, then it's not available. This is why this key is not even showing by default.

**Comment by user9209** [comment]
@skarpushin 

> Maybe you can create new/dummy private key with same properties and send it to me? 

I do not know how that key happens so can not reproduce it.
As a result we can only ignore that error.

> Maybe 8k key just exceeds restricted key size. Or maybe it's Bouncycastle limitation. Bouncycastle - is the PGP implementation I use.

Currently only some software does not support generating large key sizes, using it I have currently no problems.
Using a 32768 bit key takes 30 minutes to generate a key and encryption and decryption is slow.

Thank you for your effort
