### ISSUE TITLE
Hot Fix: fix regression introduced in 0.5.3.0 which prevented "Decrypt Text" feature from working

### ISSUE THREAD

**Issue by TheFrisianGamer** [pgptool/pgptool#174]
When trying to decrypt text with PGPTool v0.5.3.0 I get an error message (see attached file)
[help1.txt](https://github.com/pgptool/pgptool/files/2799110/help1.txt) ![screenshot_17](https://user-images.githubusercontent.com/45695624/51788799-624a1c80-2182-11e9-976e-5c1abdd312aa.png) This only happens when trying to decrypt text.

**Comment by skarpushin** [comment]
@TheFrisianGamer , I'll apply hotfix ASAP, thanks for letting me know!

**Comment by skarpushin** [comment]
@TheFrisianGamer , I've created hotfix. You can download it here: https://github.com/pgptool/pgptool/releases/tag/0.5.4.0
