### ISSUE TITLE
Cannot decrypt extracted keys

### ISSUE THREAD

**Issue by Charsy89** [pgptool/pgptool#178]
I extracted a public key for a recipient (file extension being .asc).
When I tried to decrypt it, it gave "Cant determine file format, cannot decrypt).
![image](https://user-images.githubusercontent.com/28523197/55701033-e264dd80-598e-11e9-94fa-7887af0732cc.png)
Both of which were done with PGPTool.
PGPTool 0.5.4.0, Windows 10.
Could I be doing something wrong?
Edit: This does not occur when encrypting/decrypting a normal file.

**Comment by skarpushin** [comment]
@Charsy89 , What are you trying to achieve? 
Key files are not meant to be decrypted.

**Comment by Charsy89** [comment]
what's the point of extracting them if they can't be decrypted? -.-

**Comment by skarpushin** [comment]
@Charsy89, you extract public key so that you can share it with other people, who will use it to encrypt files for you. 
For more details please refer to https://pgptool.github.io/#faq
Also here you can find few videos which explain how to perform main operations: https://pgptool.github.io/#help
