### ISSUE TITLE
Feature Request: Deprecate Java 8 Requirement

### ISSUE THREAD

**Issue by beems** [pgptool/pgptool#179]
Due to the requirement of Java 8 for PGPTool, we will need to buy Java SE 8 licenses from Oracle at a cost of $30/year. I'd rather give that money to the developer of PGPTool than to Oracle, so are there any plans to migrate the application beyond Java 8? Otherwise, we did try OpenJDK and Amazon Corretto, but the application, upon opening, still prompted for Java 1.8.0*.

**Comment by beems** [comment]
Closing issue. While it would be nice to not require JRE on Windows, I did get it to work with Amazon Corretto x86 (x64 did not work).

**Comment by skarpushin** [comment]
@beems , I'm glad that you've found a workaround for a time being. 
I'm going to re-open this feature request. Most likely changes will be required in launch4j project, because pgptool itself doesn't care about underlying jdk implementation, while launch4j does. 
I'll check into this once I have time for it.

**Comment by skarpushin** [comment]
Relevant launch4j feature requests:
- https://sourceforge.net/p/launch4j/feature-requests/127/?page=1&limit=25#fc9e
- https://sourceforge.net/p/launch4j/feature-requests/103/

**Comment by skarpushin** [comment]
@beems I've added the capability for pgptool.exe to look into JAVA_HOME env variable. This change is available only as a part of pre-release, which you can try out here: https://github.com/pgptool/pgptool/releases/tag/0.5.9.0
I guess that's the best I can do for now to fulfill your initial request. 
Please let me know if you have any feedback.
