### ISSUE TITLE
Store of Private Keys

### ISSUE THREAD

**Issue by jhuesser** [pgptool/pgptool#202]
Where are the private keys stored, if you generate them via pgptool?
We'd like to install this software on a Citrix environment with multiple hosts. Is the key saved to the profile, so the user doesn't have to import it again if he lands on e different host?

**Comment by skarpushin** [comment]
@jhuesser , pgptool will store it in `%userhome%/.pgptool/configs/PgpKeysRing` file.

**Comment by skarpushin** [comment]
@jhuesser , no problem. I've created and Improvement (#203) based on your question. One of the concerns I have is concurrent usage of the same KeyRing on 2 hosts. Please let me know if there are any issues in such scenarios.
