### ISSUE TITLE
pgp version underneath the pgptool

### ISSUE THREAD

**Issue by mailtosonyia** [pgptool/pgptool#205]
Hi wanted to know the open source pgp version running behind the scene of the windows pgp tool. Can some one please help.

**Comment by skarpushin** [comment]
@mailtosonyia , PGP Tool is using Bouncy Castle 1.56 
reference: https://github.com/pgptool/pgptool/blob/5a6ee61f274b35f6e742e259ed9c5ea71fa65b5c/pgptool-gui/pom.xml#L124

**Comment by mailtosonyia** [comment]
thank you @skarpushin, is there a command line utility option for PGP Tool, we are trying to understand the difference between encryption by  PGP tool  to GnuPG command line encryption. If possible would you help me with translating the encryption part of PGP tool into GnuPG commands with the parameters used.

**Comment by skarpushin** [comment]
@mailtosonyia , PGP Tool is aimed at providing very easy-to-use graphical user interface. It does not provide command-line interface.
