### ISSUE TITLE
PGPPublicKeyRing found where PGPSecretKeyRing expected

### ISSUE THREAD

**Issue by Amirkhon** [pgptool/pgptool#209]
Hi Sergey, thank you for such a great tool!
I have an issue getting secret key from private key generated by and exported from the tool.
```
final PGPSecretKeyRingCollection pgpSec = new PGPSecretKeyRingCollection(PGPUtil.getDecoderStream(keyIn), new BcKeyFingerprintCalculator());
```
throws
```
org.bouncycastle.openpgp.PGPException: org.bouncycastle.openpgp.PGPPublicKeyRing found where PGPSecretKeyRing expected
```
How can I get private key?

**Comment by skarpushin** [comment]
@Amirkhon , exported private key contains both -- public and private keys. Please refer to the https://github.com/pgptool/pgptool/blob/master/pgptool-gui/src/main/java/org/pgptool/gui/encryption/implpgp/KeyFilesOperationsPgpImpl.java class. This is how I read and write PGP keys. Particularly `readKeyFromStream` and `exportPrivateKey` methods.
