### ISSUE TITLE
Feature request: ability to create key without passphrase

### ISSUE THREAD

**Issue by skarpushin** [pgptool/pgptool#223]
feature request from youtube video comment

> Great tool, but I see the passphrase (password) is mandatory in order to decrypt. You can generate a pgp pair key without one. can you make a patch in order to make it optional?

**Comment by Egor-Skriptunoff** [comment]
The feature is useful, but it seems to be not 100% implemented yet.  
I can successfully create a private key protected by empty passphrase, but it is impossible to decrypt text using this private key.  
![pwd_required_for_pwdless_key](https://github.com/pgptool/pgptool/assets/19153610/cffed77b-0cea-4970-bfc7-24ea1fbc9519)
