### ISSUE TITLE
Wiki Upate

### ISSUE THREAD

**Issue by timetoseek** [pgptool/pgptool#226]
Please see attached updated wiki docs.  Also, please update the project name in the Wiki Home page, as per the screen print below. Thank you!
![wiki_home](https://user-images.githubusercontent.com/26972658/80537066-42427380-8958-11ea-89a9-a1e2f933dd87.jpg)

---
[Project charter.txt](https://github.com/pgptool/pgptool/files/4548422/Project.charter.txt)

[Manual installation- updates to instructions.txt](https://github.com/pgptool/pgptool/files/4548423/Manual.installation-.updates.to.instructions.txt)

**Comment by skarpushin** [comment]
@timetoseek , thank you.
