### ISSUE TITLE
PGPTool Decrypt Button

### ISSUE THREAD

**Issue by Jearime** [pgptool/pgptool#231]
Hello,

We are attempting to use PGPTool to decrypt medical records that are sent to us. We sent them a key and they have used it to create their file. When we get receive the finished file, add it to PGPTool, the button remains grayed out for decryption. Why is that?

**Comment by skarpushin** [comment]
@Jearime , because input values are either incomplete or incorrect (i.e. if you failed to provide correct password for the key, or didn't provide some other info). Can you please send me the screenshot?

**Comment by Jearime** [comment]
Actually that probably answers the question enough. It was already my suspicion that the original key setup wasn't done correctly, but I wanted to make sure I had that correct. Your thoughts corroborates my suspicion. I will attempt to have that person create a new one again and we will test. I might be back tomorrow after the test to close / bring further details if we have issues.

**Comment by skarpushin** [comment]
@Jearime , sure. Good luck!

**Comment by Jearime** [comment]
The issue ended up being the person creating the PGP file had a wrong or bad key. It has been resolved by creating a new key and the file creator using that key. Thanks for the help.
