### ISSUE TITLE
Feature: Copy Key ID to clipboard

### ISSUE THREAD

**Issue by Egor-Skriptunoff** [pgptool/pgptool#233]
Currently there is no way to copy-paste Key ID from PGPTool: you can see it but can not copy, it's a user-unfriendly behavior.  
Please add "Copy Key ID to clipboard" action to the context menu in the "PGP Keys List" window.  
Or (a better approach) make any cell in the keys-list grid copyable with the mouse.

**Comment by skarpushin** [comment]
Good point! Thank you for suggestion.

**Comment by Egor-Skriptunoff** [comment]
As I see, the problem is already fixed.  
Unlike in 2020, now "Keys List" window allows user to select (by mouse click) and copy (with `Ctrl-C`) whole line of information about a single key, including Key ID.  So, now I can easily copy Key ID to a text editor.  
Thanks, the issue is solved.
