### ISSUE TITLE
pgptool on MacBook Pro 2019 (dual graphic adapter)

### ISSUE THREAD

**Issue by gortsche** [pgptool/pgptool#241]
Hi,

I have started to use pgptool on MacBook Pro 2019 and it kept crashing at launch and the logs did not help really to troubleshoot. I was running it successfully on my iMac (exact same setup) with no glitch.
Now the MacBook Pro is fitted with 2 graphic cards (Intel UHD Graphics 630 and AMD radeon pro 5300M) with an automatic graphic switching feature in MacOS that allows to save battery life. If an app supports / requires heavy graphic features, it will switch to AMD Radeon, otherwise it stays or comes back on the Intel one.

For pgptool to work, auto graphic switching must be disabled, or it always crashes. I cannot really explain why.
When MacOS auto graphic switching is disabled, when starting pgptool as the Mac is using Intel adapter, pgptool will then push the Mac to switch to AMD radeon adapter. It works. but quitting pgptools will not cause the Mac to go back using Intel adapter.
When MacOS auto graphic switching is enabled, when starting pgptool as the Mac is using Intel adapter, pgptool will crash and log file will be created. I am attaching the log.

[hs_err_pid3372.log](https://github.com/pgptool/pgptool/files/5403939/hs_err_pid3372.log)

**Comment by skarpushin** [comment]
@gortsche , sorry to hear that you're experiencing issues with PGP Tool.
Unfortunately I will not be able to reproduce this issue nor investigate based on log file you've attached.
But I can try to investigate it based on application log file. Can you please do the following:

1. Make sure PGP Tool is not running
2. Delete `pgptool-gui.log` that is located in your user's home folder
3. Start PGP Tool (expect it to crash)
4. Locate `pgptool-gui.log` and review it to make sure you're comfortable with sharing this file, feel free to replace sensitive data (if any) with some character, i.e. `X`
5. Send me this log file to sergey.v.karpushin@gmail.com

**Comment by skarpushin** [comment]
@gortsche , I've took a look at logs that you've shared separately and it looks like it is a JRE failure. It is not clear though whether it is common bug or some edge case that is triggered by the application behavior.

Is it possible for you to install other JRE (either latest version of current one) or maybe completely other JRE i.e. https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/macos-install.html ?

**Comment by gortsche** [comment]
Good morning,

 

The latest release of JRE issued by Oracle yesterday actually sorts out the problem ! sorry for bugging you on this one.

I’ll still try with the Amazon one

 

Regards

 

Guillaume

**Comment by skarpushin** [comment]
No problem :-) I'm happy that helped!
