### ISSUE TITLE
PGP Tool Can't Access Jarfile

### ISSUE THREAD

**Issue by TLyrics95** [pgptool/pgptool#242]
I am brand new to the PGP Tool and once I installed it and opened the program, it suggested Java updates. I completed the updates and it is now saying Error: Unable to access JarFile C:\\users\name\onedrive\desktop\pgptoolgui-0.5.9.2.jar. 

Any help is greatly appreciated!

**Comment by skarpushin** [comment]
@TLyrics95 , please provide exact steps which you're performing and what you're experiencing.

**Comment by 0xHubert** [comment]
Did you solve this? I am having the same problem

**Comment by skarpushin** [comment]
hi @0xHubert, please provide exact steps which you're performing and what you're experiencing.

**Comment by 0xHubert** [comment]
you know what i know the issue it tried to access an executable on my one drive which i didnt have running! sorry
