### ISSUE TITLE
PGPTool doesn't recognize my key

### ISSUE THREAD

**Issue by Herringboned** [pgptool/pgptool#246]
Hello everyone,

I've been using PGPTool for a while now and it's been great... until this week. I tried to use it once again to log into a website where I use PGPTool for double authentification and it did not work.

Usually I copy paste the text I want to decrypt and PGPTool instantly recognizes the key concerned and I only have to type in my password.

But now, PGPTool says "none of the private keys in your key ring is suitable for decryption of this message" even though I did import the right key and it appears on the key ring...

I look forward to reading any helpful answers.

**Comment by jasperSha** [comment]
I'm having the same issue. It only recognizes my key so I can encrypt/decrypt using mine. But it's unable to recognize any public keys that I download. I've been looking through the error log and I think I've traced it down to

org.bouncycastle.openpgp.PGPRuntimeOperationException: Iterator failed to get next object: invalid header encountered

Someone else had a similar issue at [](http://bouncy-castle.1462172.n4.nabble.com/Problem-with-JcaPGPObjectFactory-throwing-exceptions-if-iterating-too-far-td4658093.html)

From what I understand, JcaPGPObjectFactory has issues when using an iterable object instead of only calling nextObject(), but PGPTool is using the .next() on the...well iterable, here in EncryptionServicePgpImpl.java file, which is also where the stack trace seems to lead to:

`for (Iterator iter = factory.iterator(); iter.hasNext();) {
				Object section = iter.next();
				log.debug(section);

				if (section instanceof PGPEncryptedDataList) {
					PGPEncryptedDataList d = (PGPEncryptedDataList) section;
					HashSet<String> ret = new HashSet<>();
					for (Iterator dataIter = d.getEncryptedDataObjects(); dataIter.hasNext();) {
						Object next = dataIter.next();
						if (next instanceof PGPPBEEncryptedData) {
							throw new SymmetricEncryptionIsNotSupportedException();
						}

						PGPPublicKeyEncryptedData data = (PGPPublicKeyEncryptedData) next;
						ret.add(KeyDataPgp.buildKeyIdStr(data.getKeyID()));
					}
					log.debug("Possible decryption with IDS: " + Arrays.toString(ret.toArray()));
					return ret;
				}
			}`

To be honest I'm barely conversant in Java, so that's as far as I understand it. Hopefully the creator can chime in.

**Comment by skarpushin** [comment]
@Herringboned @jasperSha , thank you for information. Once I get back from vacation/holidays I take a look at this issue. By any chance -- can you please send me those public keys OR tell me which application was used to create those keys? I need to be able to reproduce this locally.

**Comment by jasperSha** [comment]
here's a public key
https://pastebin.com/raw/8xx4fv4g

and here's the message

-----BEGIN PGP MESSAGE-----
hQIMAwAAAAAAAAAAAQ/8DyCQV73HGzjvTOyMbO+AgTYT36uiqVOoLWl9cjFFlemW
xIs3XmNjaAFJ5W3QFb2BUowTs2YPopA9hdaUwe5irp9V8GoZCuRsMT29VjqinlZ/
QbHGuF1nsRzkiQZGUhEL1mwBYrFenbYTK5ShTBSUsM2HT61bUiUrbTpI5/XB+TCq
rhsjs4c/C1pBAivcSnAYsaoC8H/NVTIp7AUAFnvJFGinFJNsNknM+Vo7EZeBPU2G
g9hQ03NIKTziqwApR/n0AZbZVuTEfPugHhDCauY9UnOpLeWMDrupWaNPhceUaKtC
jRwjTxXSvvPAGCxghg88vx7Bk83qopNl6PxMu83lYVr6MSAAoTvMoax+8rr42EjR
o8ASeFEIVywskSP0xmbI0pXV23FS6bsLpInGQtoO5xqBFhMNq2yGtIVQroVScstn
FK0VR1W+NcO8rhN6zaK2jS6Exfhy+FSAFZqLFu+YHwXt5HtSwXt/mR290Wx0FN1u
/9CnIGjuRaF0OUNiyO0XIYwSPLoR5y/GSAsqBdlxjhZEdHWE2yqEgZQuiTrcmzRH
70vfAcnnSp1fxvXcDcTdVXes4DaT9VUrwTmMsyJ5wtLYMNey8kllmQXKheEed9yL
JgQs3TqP6C9nfDDzRkF+3ngmE8lUf1oq+67q4mKjVLIROdeVOVaRYFkGo8yXXZ6F
AgwDT6nyJ9n6M58BD/0aHwx/XL9piO3TzzygOUCnKwiNzRheujp1UcmVisYNli6r
5lSWgzGyBWq/p2FtOmFoom2TJd027RpKs/iv9anrTMedFmzfH+A9jiyNlfN4foK1
SSMnF8QqfZzW0pXvTquwBlyUCkZncdn8LwWlIFlZEY/ByAT+QLQ5P3sS/VgTbGxT
YSQ8LeCkpCNuQvfA44cIXptoics9OJydY+FZqwDVvOJpu+tsuSWmF/Nx+JVmQJtt
zz1gZ/MRCGZkteraUibrIRpi2m3Qpb6FIdgKzwAy2DgGAmbhrZhJzwEvawI86iuB
TX1oq+43Dip6Pib6f/fsmsBmoaNCk/cf9OlHFTJzwM+5xPjm+r9T+dZNMubDInIl
aXGVv8+iLJ0wPMU14FYSDpeBbdPmxWv+ifBe5TnyCP7tChZzo32KQMhKnp4XUW6R
91Pk651+ImRF5zMiBHsyToCtZDfZDt7+tSry60ltJUli8rXMX9qNbX/BmbteGiiS
TCPRmV3YX/M29oSSKj17vHxdQm8QPse7l9XDhN3cYCOrxm6EWipTZ0lyCNHs9SiX
kOXhVtRu2RrhTwXBTtEIa/K8rWs2A30GtrCUlaGptD6cochBMS7HaMzu25hUuNkE
RzulRaTicOJ1EmDWxKqlxwai4Wg6Yhfx/WJfB0Sy4+XO+KHV5bAU4ASCkcPLj9LA
WwHx/nSRMseAD+0lhLcUoEow0NjcwLp+PWhMBiX7pIE5ZkErF/3ZEUTjzT9IinsR
vOBPeGhKQRAs7h1S8tCAuCMM9gDmaAmgs/K6pFFRPUsaC6PFzr7WhIv/fACJDgFe
wwouJ0kZ6IhEn6dIvwJR2cwaxqG7w1jDPUbP/thlUyaMKpOQFqkmgRNoLSnAbY2p
dLslNMN6o5aWxlGbFNEGbY828lIsPATZMKw+EGlQtolmw8acp/yxz9va4BUIvNVQ
LHpbrvJxPIx1W8llvW+2S8275+oLaHmnBbURIahk0K6fIsIirPhevyysZVPurIxm
KJWFH9JsFLYqTsvaS2N6pgmAaLGjm6A8q9UNXn/HQXHs+D7CFeLEwyjvlzc= =3GUx -----END
PGP MESSAGE-----

so this one is a slightly different error from the other key I was trying
to use. In the "Can be decrypted by: " box it shows the key ID, but I can't
click it and I can't click on decrypt. The event log says:
"Possible decryption with IDs: [0, <keyID>], so it seems to see it? but the
GUI gives me the error saying none of the keys are suitable and it can't
seem to read it for some reason.

**Comment by jasperSha** [comment]
You know what, I might have misunderstood the purpose of the tool. I'm just trying to verify a pgp signature; is that the same as attempting to decrypt a message? I have a public key and a signature, and using online tools to verify it works, but not to "decrypt" the message.

**Comment by skarpushin** [comment]
@jasperSha , no. Signature verification and Decryption are 2 different actions. 

Signature verification will be implemented as a part of https://github.com/pgptool/pgptool/issues/18 planned feature.

**Comment by skarpushin** [comment]
I cannot reproduce this. 

1. I've created key using command-line gpg application
2. imported public key into PGP Tool
3. Encrypted text for this public key and for my private key
4. Decrypted same text using my private key

No issues faced. 

If somebody bump into this again -- please share details so I can investigate.
