### ISSUE TITLE
PGP tools library for C#

### ISSUE THREAD

**Issue by aalvarezc74** [pgptool/pgptool#247]
Hi there,

I'm wondering if you offer as a product to purchase the PGP libraries that you use in your PGP Tool to be integrated in NET projects?

I have been trying other PGP libraries for a NET project, but so far only the files encrypted using your PGP Tool works fine!.

**Comment by skarpushin** [comment]
@aalvarezc74 , PGP Tool is using a third-party library to perform all PGP operations. 
This library called Bouncy Castle, and they [seem to offer](https://www.bouncycastle.org/csharp/index.html) .NET version of this library.
