### ISSUE TITLE
PGPTool export Private key, then import to keyring, why always show it's key pair not private key.

### ISSUE THREAD

**Issue by irispinkgirl** [pgptool/pgptool#255]
I exported Private key via PGP Tool, then import to keyring, but it always show as key pair not private key.
I have checked the content of private key , it's only Private key.
I tested to encrypt a file with client's public key with my private key (show key pair in pgptool) , we got "Failure :  File not signed" , it's mean the file cannot be decrypted.
kindly advise how to only import private key, thanks.

**Comment by skarpushin** [comment]
Something is not right in this sentence, especially the last part: _I tested to encrypt a file with client's public key **with my private key**_.

Private key is used to decrypt data. You are not using private key when encrypting. So I'm not sure what exactly you did here

Also

> "Failure : File not signed"

Indicates that you're using some other application that require a signature as well. But PGP Tool is yet to have signature feature implemented (see https://github.com/pgptool/pgptool/issues/17). No signature is created with encrypting files in PGP Tool for now.

p.s. private key contains enough information to encrypt and decrypt, that is why PGP Tool call is it Key Pair.
