### ISSUE TITLE
Azure Data Factory - PGP encrypt

### ISSUE THREAD

**Issue by devid74** [pgptool/pgptool#258]
Hi
Need to encrypt a file in an azure data factory pipeline. Has anybody done this before and if so what is required? as I am unable to find anything online.

Thanks

**Comment by skarpushin** [comment]
"PGP Tool" is purely a GUI tool for encrypting and decrypting files/text. 
"Azure data factory pipeline" is some kind of background server-side type of processing. 

These two will not work together, sorry. 
I'm not an Azure expert so I cannot give you an advice on where to look.
