### ISSUE TITLE
Hello technician, I need your help on a very urgent matter

### ISSUE THREAD

**Issue by Johnny329328** [pgptool/pgptool#261]
Because I am using this encryption program for the first time, a few days ago my computer broke down and I had to reinstall the system, I reinstalled the system without exporting the key and backing it up, but before I installed the system, I had stored the GPG folder and the main program pgptool on my C drive, why is all the data in pgptool gone now when I open it, because I still have more than $2000 in my wallet in some marketplace that I can't get back, please help, thank you.

**Comment by skarpushin** [comment]
@Johnny329328 , I'm afraid you deleted all the data on C drive. 

> but before I installed the system, I had stored the GPG folder and the main program pgptool on my C drive

If you reinstalled the system on C drive (which involved formatting of the said drive), then all data on C drive was deleted. 

I "hail marry" for you would be to attempt to recover files using specialized tools. I have no experience in such, so cannot give any particular recommendations.

**Comment by Johnny329328** [comment]
Hi, I found a document the other day that has a lot of data about PGPtool in it. I am not sure if I can recover the data,, can you help me to see. Help me, thanks!### 

> 
[pgptool-gui.log](https://github.com/pgptool/pgptool/files/7820261/pgptool-gui.log)

- > [`****`](url)

**Comment by skarpushin** [comment]
@Johnny329328 the only thing I can tell from this logs is that config files (including key ring) was stored in `C:\Users\Administrator\.pgptool` folder. If you could recover this folder or at least file `C:\Users\Administrator\.pgptool\PgpKeysRing` then you'll get your keys back
