### ISSUE TITLE
Avast malware detection on pgptoolgui-0.5.9.2.jar

### ISSUE THREAD

**Issue by bhafer** [pgptool/pgptool#262]
Hello. Today, I had Avast trigger a malware detection on pgptoolgui-0.5.9.2.jar and I'm guessing this might be a false positive?

Windows 10
Avast Version: 21.11.2500 (build 21.11.6809.528)
Virus Definitions: 220206-16

File: C:\Program Files (x86)\PGP Tool\pgptoolgui-0.5.9.2.jar
Detection: Java:Malware-gen [Trj]

**Comment by skarpushin** [comment]
hi @bhafer can you please confirm exact location where you downloaded `pgptoolgui-0.5.9.2.jar` file from?

**Comment by bhafer** [comment]
Yes, it is downloaded from here on github:

> sha256sum pgptoolgui-0.5.9.2-git.msi
da44f7ff2ad9ff26cdeca97dda6ff36f7b40b0886a3ed26e822dba0cb2e2fb11 *pgptoolgui-0.5.9.2-git.msi

Also, I have submitted the file to Avast for review as a possible false positive. But I wanted to inquire here if there was possibly any information.

**Comment by skarpushin** [comment]
@bhafer I've just checked binaries on my build machine (exactly same binaries uploaded on github) and checksums are matching the ones you've posted. 

```
certUtil -hashfile pgptoolgui-0.5.9.2.jar SHA256
SHA256 hash of pgptoolgui-0.5.9.2.jar:
19dbf800d14411a76727229120ccea8ad02e4f4d8876695ca7e14ccef86b75e0

certUtil -hashfile pgptoolgui-0.5.9.2.msi SHA256
SHA256 hash of pgptoolgui-0.5.9.2.msi:
da44f7ff2ad9ff26cdeca97dda6ff36f7b40b0886a3ed26e822dba0cb2e2fb11

```

So with that it looks like files were not altered. 

My best guess is that it is either a complete false-positive, or they're scanning some of the libraries and checking if there are vulnerable versions, like recently infamously known log4j2 vulnerability. But even so, such vulnerabilities are only applicable for server code, while PGP Tool is a desktop client-side code only.
