### ISSUE TITLE
help please i used i golder..

### ISSUE THREAD

**Issue by jtomli710** [pgptool/pgptool#268]
so i set up my pgp keys through igolder it just shut down and when i set up my keys i didnt set it up using a passphrase how can i bypass it asking me for a passphrase because the original key NEVER had one

**Comment by skarpushin** [comment]
@jtomli710 
IIRC PGPTool can work with keys with no passphrases. Which version are you using?
I just checked on version 0.5.9.2 - and yes, it handles keys with no passphrases just fine.

**Comment by jtomli710** [comment]
Can you send me a link to it for download any chance 


Sent from Yahoo Mail for iPhone


On Thursday, June 2, 2022, 4:35 AM, Sergey Karpushin ***@***.***> wrote:




@jtomli710
IIRC PGPTool can work with keys with no passphrases. Which version are you using?
I just checked on version 0.5.9.2 - and yes, it handles keys with no passphrases just fine.

**Comment by jtomli710** [comment]
I was just using kleopatra 


Sent from Yahoo Mail for iPhone


On Thursday, June 2, 2022, 4:35 AM, Sergey Karpushin ***@***.***> wrote:




@jtomli710
IIRC PGPTool can work with keys with no passphrases. Which version are you using?
I just checked on version 0.5.9.2 - and yes, it handles keys with no passphrases just fine.

**Comment by skarpushin** [comment]
https://github.com/pgptool/pgptool/releases/tag/0.5.9.2
