### ISSUE TITLE
Windows10 antivirus prevents public key creation

### ISSUE THREAD

**Issue by jbowen28** [pgptool/pgptool#282]
Hello,

My Windows10 Norton antivirus program is preventing the pgptool from running and I lost my keys as a result.  I turned the Norton antivirus program off and now I cannot create a public key with a private key.  The Key Ring shows only a private key when I try to create a key pair.  I tried reinstalling the pgptool program 4 times with Norton antivirus turned off and I still cannot create a public key with a private key.  The pgptool only creates a private key as shown in the Key Ring.  Do you have any suggestions?

**Comment by jbowen28** [comment]
Hello,

My wife is having problems with the pgptool on her Windows10 computer.  I am using the pgptool successfully on my MacBook and we have been using the pgptool to exchange encrypted files successfully until now.  If my wife use another PGP tool like Gpg4win, will I be able to use her Gpg4win generated public key with the pgptool to allow her to decrypt the encrypted file?

**Comment by skarpushin** [comment]
@jbowen28 hi. I'm both surprised and sorry to hear that. 

- "preventing the pgptool from running" -- how does it look like? Can you share screenshot please? 
- "I lost my keys as a result" -- why you've concluded that keys are lost? Keys are stored in `c:\Users\USERNAME\.pgptool\configs\PgpKeysRing` file (replace USERNAME with your user name). Did Norton antivirus deleted this file? 
- "will I be able to use her Gpg4win generated public key with the pgptool to allow her to decrypt the encrypted file?" -- this should work, yes

Did you backup your keys somewhere? Maybe you can import them from backup?

**Comment by jbowen28** [comment]
Hello,
Thanks for your prompt response.  My wife somehow was able to get the pgptool working again and we exchanged encrypted files again.  Thanks!
