### ISSUE TITLE
PGP file DECRYPTION problem 

### ISSUE THREAD

**Issue by freerider21** [pgptool/pgptool#285]
Hi guys , after e ncryption of file with data I ve saved 2 files for decryption .pgp and .asc . Now PGPTOLL doesnt recognize any key to decrypt a file , is .asc a  private key file ?

**Comment by skarpushin** [comment]
@freerider21 sorry, I'm not getting your question. Can you please describe step-by-step?

1. Encrypt file A.txt into B.pgp with key K
2. etc...

Actual behavior: ???

Expected behavior: ???
