### ISSUE TITLE
Log4j vulnerability

### ISSUE THREAD

**Issue by BrianFreemanAtlanta** [pgptool/pgptool#291]
Using version 0.5.9.2 on windows. Identified log4j vulnerability in application. I believe dependency needs to be updated to remove vulnerability. In the meantime I have to uninstall to keep my computer safe and compliant. :-(

**Comment by skarpushin** [comment]
I'm not sure which log4j vulnerability you're referring to. PGP Tool is a desktop application, not a web application. Therefore majority of vulnerabilities are just irrelevant.
