### ISSUE TITLE
Cannot see files on MacOS

### ISSUE THREAD

**Issue by JirkaKrivanek** [pgptool/pgptool#292]
I am on MacOS 13 (.3.1 for now). When I click on "Encrypt file", I get the file selector dialog. I go to the Desktop, where I have my file ready for encryption. 

I cannot see any Desktop content.

Well, it probably has to do with the Apple restrictions: Most of the applications pop up the dialog requesting access to the "xxx" folder.

I also tried to go to the "System Settings" => "Privacy & Security" => "Files and Folders", but the PGPTool app is not there.

For now I am switching to my virtual Microshit Willows, but that is quite annoying...

Any idea how to use this app on MacOS?

**Comment by skarpushin** [comment]
@JirkaKrivanek I do not have MacOS at hand. I'll try to fetch one and try to reproduce.

**Comment by HimanshuSharma-Angel** [comment]
@skarpushin its not an issue. This issue is entirely related to allocating permissions on the OS level. 
I have all the permissions as allow nd it worked for me.
