### ISSUE TITLE
Using PGPTool to Sign file?

### ISSUE THREAD

**Issue by Jeffrey-Miller** [pgptool/pgptool#301]
Hello Sergey, 
I am a new user and would like to ask if PGPTool can be used to sign a file and allow validation by a receiving party using the sender’s public key?  If not a "built-in" feature, is there a procedure/protocol which can be followed using the current PGPTool? 
Regards, Jeff

**Comment by skarpushin** [comment]
Hello @Jeffrey-Miller 

This feature is planned, but not implemented yet: https://github.com/pgptool/pgptool/issues/17
