### ISSUE TITLE
Fix installer so that Windows 10 wont show SmartScreen warnings

### ISSUE THREAD

**Issue by skarpushin** [pgptool/pgptool#62]
![windows smart screen warning 0](https://cloud.githubusercontent.com/assets/4069181/22787743/528779e8-eeab-11e6-9bba-072416373c8c.png)
![windows smart screen warning](https://cloud.githubusercontent.com/assets/4069181/22787744/52a18586-eeab-11e6-9a77-dd4656d120b7.png)

It might also help to sign jar file: https://blog.frankel.ch/jvm-security/2/#gsc.tab=0

Relevant links:
* http://stackoverflow.com/questions/12311203/how-to-pass-the-smart-screen-on-win8-when-install-a-signed-application
* https://blogs.msdn.microsoft.com/ie/2012/08/14/microsoft-smartscreen-extended-validation-ev-code-signing-certificates/
* http://www.cacert.org/

**Comment by jstaylor11** [comment]
First off, I absolutely love this tool and I am very grateful for the time you put it. But it seems like an incredible oversight (and a little ironic) not to have the installation file or the executable file for this signed, especially considering the nature of the of the product. I went back and looked and even version 0.4.0.0 was not signed.

I looked into it and  you can now do file and installation code signing integrated with GitHub and Microsoft/Azure for as little as $9.99 a month, and even better it can be automated. 

https://www.hanselman.com/blog/automatically-signing-a-windows-exe-with-azure-trusted-signing-dotnet-sign-and-github-actions#:~:text=Someone%20told%20me%20that%20Azure%20Trusted%20Signing,%2D%20it's%20less%2C%20but%20it's%20still%20non%2Dtrivial.

https://melatonin.dev/blog/code-signing-on-windows-with-azure-trusted-signing/#:~:text=Trash%20those%20overpriced%20third%2Dparty,always%20give%20it%20a%20try.

Again, thank you for all the time you have put into this! I hope this doesn't at all come across as criticism, but as a grateful user trying to help.

**Comment by skarpushin** [comment]
Hi @jstaylor11, I'm happy to hear that you really enjoy this tool :-)

I totally agree that it would be really nice to have a signed installer, but my first attempt was kinda unsuccessful because first of all I faced unexpected bureaucracy while dealing with the certificate issuer, and second of all I'm not earning anything from this tool. I get a "buy me a coffee" here and there, but $10 a month means $120 a year, which I'm not ready to pay together with all this unpleasant bureaucratic hassle. Again, as you can see, this software is completely free and there are no ads.

Maybe these days they've made it simpler (compared to 2017), and once I have some additional spare time (which I don't at the moment), I'll revisit this task.
